server:
  port: 6666


spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 1274969770
    lettuce:
      pool:
        max-idle: 10
        min-idle: 5
        max-active: 50
        max-wait: -1ms
    timeout: 10000ms

lock:
  server:
    server-type: single
    single:
      address: redis://${spring.redis.host}:${spring.redis.port}
      password: ${spring.redis.password}

  more:
    servers:
      -
        server-type: single
        single:
          address: redis://${spring.redis.host}:${spring.redis.port}
          password: ${spring.redis.password}
      -
        server-type: single
        single:
          address: redis://192.168.10.5:6379
          password: mUWPMPpWyv8I069o
  config:
    lock-watchdog-timeout: 10s